version: "3.8"

services:
  neovim:
    image: neovim_image
    container_name: neovim_container
    hostname: neovim_server
    ports:
      - "9000:9000"
    build: .
    volumes:
      - ./:/root/ws
    command: /bin/bash
    working_dir: /root/ws
